### ISSUE TITLE
My enmity plugin will not load when I update it to 6.7.0 or 6.7.1

### ISSUE THREAD

**Issue by pancakegithub** [xtuaok/ACT_EnmityPlugin#16]
When I replace all of the relevant files in my ACT directory with the files from the update, and then run ACT, The messages in the OverlayPlugin tab (within the main Plugins tab), gives the following error. Further, this continues even if I search out the 6.6.0 version and put those files back, the only way for me to "fix" this was to do a completely fresh install of ACT.

So either I am doing something wrong when I am copying over the files or there's an issue somewhere in the files. I am making sure that I am putting all of the files into the same folders that they were in before, it just refuses to load the updated EnmityOverlay.dll

The error I get is:

2/25/2016 6:08:30 PM: Error: LoadAddons: C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin\addons\EnmityOverlay.dll: System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin\addons\EnmityOverlay.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\Program Files (x86)\Advanced Combat Tracker\OverlayPlugin\addons\EnmityOverlay.dll' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at RainbowMage.OverlayPlugin.PluginMain.LoadAddons() in c:\Users\john_000\Repos\Personal\OverlayPlugin-Compiler\OverlayPlugin\OverlayPlugin.Core\PluginMain.cs:line 210

**Comment by ezsoftware** [comment]
This line:  An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework.

Indicates the DLL was blocked by windows, before extracting the .zip, if you use the windows explorer to unzip the files, you need to right click > properties > unblock the .zip file, this will unblock all DLL's in the zip file.

Alternatively, use 7zip as it unblocks dll's for you.
